### PR TITLE
layout file - initial commit - work in progress

### PR DESCRIPTION
**Pull request by dvdlevanon**

### CODE REVIEW

**Comment by mattrose** [comment]
Sorry it took me a while to get to these, looking at them now.

**Comment by mattrose** [comment]
fixes #213

**Comment by mattrose** [comment]
So, it looks really good, but I loaded up 2-3-grid.json and seem to have gotten myself into a state where there is an [[__internal_json_layout__]] section in the config and when I load up terminal from the regular config I get this errror
```
[mattrose@sorrento terminator]$ python3 terminator 
ConfigBase::load: config format is not valid
[layouts,__internal_json_layout__,root]: parent is invalid
```

**Comment by dvdlevanon** [comment]
Hi @mattrose 

It happened to me as well, I'm looking into it now and will update soon.

Thanks for the review

**Comment by dvdlevanon** [comment]
The `__internal_json_layout__` and `__internal_json_profile__` is the internal "Fake" layout and profile created by the `--config-json` argument. 

I put them in the `config.base` to make them a first citizen layout/profile and avoiding special care across all the code base.

Unfortunately, the "Fake" layout and profile found their way to the global config file, via the `save` mechanism. Indirectly causing errors when running terminator in the regular mode.

In order to solve it, I excluded those special names from being saved to the global config file.
https://github.com/gnome-terminator/terminator/pull/214/commits/b66999618067c314d16e0d0f6d7cad2ed6dfe0f0

**Comment by mattrose** [comment]
Thanks for looking at this.  I'll pull down the new code later this morning (I'm on EST in Canada) and play with it.

**Comment by mattrose** [comment]
This looks really good.  It's well organized and only touches the core code where it has to.  Is there anything else you want to do before merging?

**Comment by dvdlevanon** [comment]
Thanks.

Before merging, I would like to:
1. Remove the example files, they should be in some doc file but not in the repository.
2. Let it run on my PC for a few days before merging, I'm working with it on a daily basis and I want to make sure nothing harm due to this change - Lets say a week from now.
3. As I'm not familiar with the development, I would be glad to hear what other steps need to be taken.

**Comment by mattrose** [comment]
1.  I think they should maybe stay in the repository, maybe move them to the data subdirectory.

2.  Definitely more soak time is always good.  I'll definitely use this more myself over the next week, just to get a feel for it.  I did notice when I was working on #217 I created new config entries, and when I ran your code, it re created the config file without them (likely because those config entries didn't exist in the code in your branch).  I'm not sure that this should be fixed, or whether it would be worth how much work it would take to fix it, because let's be honest, it would only happen to people developing terminator, but it's something to keep in mind.

3.  Unit tests would be nice, if you're comfortable writing them.  They can make sure nothing that's horribly broken sneaks in.  If you're not comfortable writing them I would definitely merge it in anyways, but more unit tests is one of my goals

**Comment by dvdlevanon** [comment]
1. I'll move them to `data`
2. Once both PRs will be merged the issue will be gone, correct?
3. Yes unit tests would be nice, not my strong side though

**Comment by dvdlevanon** [comment]
@mattrose I used it for a while, everything seems to be working fine.
I think we are good to merge now

**Comment by mattrose** [comment]
This looks great.  I'm planning on releasing 2.0 tomorrow or the day after, do you mind if I wait until after I tag and release, before pulling this in?

**Comment by dvdlevanon** [comment]
Sure fine by me, I'm using "my version" of terminator anyway. so whenever you want to pull it its fine

**Comment by mattrose** [comment]
Thanks Again!

**Pull request merged**
