### PR TITLE
Add new plugin for opening current directory using right mouse button

### PR DESCRIPTION
**Pull request by pktiuk**
Hello

I have created this simple plugin to add a feature I really missed in terminator.  

Simple opening current directory.

obraz

### CODE REVIEW

**Comment by pktiuk** [comment]
I think this plugin could be made enabled by default (after some refinement).

**Comment by mattrose** [comment]
I love it.  It's very simple and could come in handy.

**Comment by pktiuk** [comment]
I think it would be worth adding a  translation to this addon and enable it by default.  
I will later open separate PR-s for this.

**Comment by pktiuk** [comment]
@mattrose   
When can we expect a new release of terminator?  
The previous one is from April 2021 and there are many improvements which should be shipped to end-users.

**Pull request merged**
