### PR TITLE
Remove hack to ensure that focus is set.

### LINKED ISSUE #714: "Don't ask, don't tell" focus hack causes gnome-shell to freeze for seconds / Xwayland to crash
Lately I have been having these weird issues where gnome-shell freezes for second and often Xwayland crashes. I have been working with the mutter + Xwayland devs to get to the bottom of this.

Let me copy and paste the summary which I added to a related (workaround) mutter pull-request for this:

I have been seeing mutter freezing for seconds / Xwayland crashes / mutter crashes when starting terminator for a while now.

After collecting backtraces I emailed @carlosg and @ofourdan to see if we could make sense of this.

The Xwayland logs showed a crash due to running out of libwayland buffer space and the crashes actually go away with: https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/188 which makes libwayland dynamically grow the buffer.

The mutter backtrace showed mutter crashing inside meta-x11-display: update_cursor_theme(), it seems that if Xwayland crashes at the wrong moment it manages to take mutter down with it. These too appear to be resolved by the libwayland change to dynamically grow the buffer.

If Xwayland no longer crashes then things just freeze for a couple of seconds when starting terminator and after that everything works normally again.

Commenting out the g_signal_connect_object("cursor-updated", update_cursor_theme) call can be used as a workaround for the freezes.

@ofourdan has managed to reproduce this by using my ~/.config/terminator/config file. I will attach that here. For me this reproduces by just starting terminator with this config in a gnome-shell which has already had at least one other app opened. I'm on a fully up2date Fedora 37 install.

Further debugging has turned out that this is caused by repeated `gdk_window_focus()` API calls. Which lead me to: https://github.com/gnome-terminator/terminator/blob/403bf540d08920971924e522bd8395485d895581/terminatorlib/terminator.py#L349 and commenting that out indeed fixes the freezes caused by starting terminator.

It looks like to me like this workaround is causing more harm then whatever focus issue it is trying to fix., so maybe remove it?

You can reach out to the gnome-shell devs in: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2849 Where a workaround for this terminator mis-behavior is being discussed. I'm sure they would be happy to discuss a better way to deal with whatever focus issue this is trying to fix (or at least fix it under gnome-shell).

### PR DESCRIPTION
**Pull request by mattrose**
set_focus() should do the trick according to the docs, so let's just use that, and not go to extraordinary measures.

fixes #714 hopefully

### CODE REVIEW

**Comment by Vulcalien** [comment]
I lost focus on start after this. I'm on X11, Gnome, Debian 12. I'll try to fix it.

**Comment by mattrose** [comment]
> Removing the line `window.set_focus()`, it then works fine for me.

Oo, can you send in a PR with that and I'll merge it?

**Comment by mattrose** [comment]
Days like this I love GTK.  This function does the exact opposite of what the function says it does.  😛

**Comment by Vulcalien** [comment]
I think the "restore focus" feature isn't working altogether.
That part of the code is meant to focus the last active terminal in a layout, right?

If that's so, then I believe that instead of focusing the `last active window`, we should focus the last window's `last active terminal'.

**Comment by mattrose** [comment]
@Vulcalien do you have a config that can reproduce the problem, or is it now fixed with the final change?

**Comment by Vulcalien** [comment]
[config.txt](https://github.com/gnome-terminator/terminator/files/11068746/config.txt)

Here there are two windows, each with one terminal.
From what I read in the config file, the terminal named "This terminal should be focused" should be.. well, focused. Instead, the focus goes to the unnamed window (at least in my machine).

***

[config.txt](https://github.com/gnome-terminator/terminator/files/11068776/config.txt)

For some reason, having a notebook influences how the focus is chosen. In this case, it works as it should.
In other tests ([config.txt](https://github.com/gnome-terminator/terminator/files/11068779/config.txt)), it doesn't.

***

What I think it's happening, is that the window that is written as last in the config file is the one that grabs the focus, every time.
I've tried looking for the cause, but found nothing.

**Pull request merged**
