### PR TITLE
Update German and Croatian

### PR DESCRIPTION
**Pull request by milotype**
- both translations are complete

### CODE REVIEW

**Comment by mattrose** [comment]
Thanks for this.  I'll pull this in after the #13 is fixed up.

**Comment by lazyfrosch** [comment]
This now needs rebasing after #91, sorry @milotype can you take a look? Also I think I saw you leaving out some HTML tags in translation.

**Comment by milotype** [comment]
I'm not a programmer, so I don't know how I can help. 
In the translation files I sent, I could not find any HTML-tag differences between the .po file and the .pot file. Can you tell me what you found?

**Comment by lazyfrosch** [comment]
No worries, I will take care of it! We are switching to a new translation platform soon, see #90

**Comment by milotype** [comment]
@lazyfrosch @mattrose 
I'm just curious ... it seems that my changes for German and Croatian in this PR have not been merged into the master branch. The current `de.po` and `hr.po` files are still the ones before my changes, plus some changes you did with the PR _update translations #255_

Please let me know:

1. should I wait till you merge my changes, or
2. should I make a new PR with my changes for de and hr, plus the updated strings in PR _update translations #255_

**Comment by mattrose** [comment]
@milotype If you could make a new PR with your changes that would be amazing and much appreciated.  I just couldn't figure out how to merge your changes with some other changes that were made.  I'll pull it in as soon as you submit.

**Pull request closed without merging**
