### PR TITLE
issue 44, add option for case sensitive search

### PR DESCRIPTION
**Pull request by dugb**
Added regex flags to allow for caseless search
Added a Match Case checkbox to the search bar
Cleaned up a couple deprecation warnings in searchbar.py

### CODE REVIEW

**Comment by mattrose** [comment]
This looks good I'm just going to run a few checks first

**Comment by mattrose** [comment]
Found one traceback while running this under Python 2.7
```
Traceback (most recent call last):
  File "/home/mattrose/terminator/terminatorlib/searchbar.py", line 122, in match_case_toggled
    self.regex_flags_pcre2 = (regex.FLAGS_PCRE2 | regex.PCRE2_CASELESS)
TypeError: unsupported operand type(s) for |: 'NoneType' and 'int'
```
Is there a different syntax for setting flags in Python2 than python3?

**Comment by dugb** [comment]
Gotcha.

I'm thinking that issue should also pop up with python3.

regex.FLAGS_PCRE2 will be `None`, if the system does not have PCRE2 regex support.  in which case it would fall back to using the GLIB regex.

I'll add a try/except to catch the TypeError.

**Comment by mattrose** [comment]
Awesome, thank you.  I think you're right.

**Comment by mattrose** [comment]
Thanks @dugb this is great!

**Pull request merged**
