### PR TITLE
Unzoom terminal on interaction

### LINKED ISSUE #550: Switch focus and splits don't work when terminal is zoomed
**Is your feature request related to a problem? Please describe.**
When a tab has few terminals and one is zoomed, switching to any direction doesn't work. There are different approaches in different emulators:

- tmux cancels zoom and switch to another pane
- kitty remains zoomed, but switch the pane to the next/previous one

**Describe the solution you'd like**
I'd prefer tmux approach, when focus change is triggered, it's better to zoom out the current terminal and then switch

**Describe alternatives you've considered**
Kitty's approach would work as well. The zoom can be preserved during a terminal focus switch

**update**: the same case is for splits. It seems logical to me to exit zoom mode and split terminal. And the same for tab switching.

### PR DESCRIPTION
**Pull request by Vulcalien**
Fixes #550

These changes make a zoomed/maximized terminal unzoom on interactions such as: creating a new tab, resizing the terminal, splitting it etc...

There are still problems with two of these interactions: rotating the terminal and moving to another terminal.
The function `get_allocation()` returns `(width: 1, height: 1, ...)` right after an unzoom.

The bug can be replicated with a few terminals (I use one on the left, one top-right, one bottom-right). Zoom the bottom-right one and try to rotate or move to the top-right terminal.
What I get for the rotation is that one terminal is big, the other two are very small.

### CODE REVIEW

**Comment by Vulcalien** [comment]
Now it works, but there is an annoying bug: after an unzoom, the terminal is moved by a single pixel, making the navigation after an unzoom inconsistent. It's a different issue, so I'll see if I can fix that with another PR.

**Comment by mattrose** [comment]
So, I have to admit, I'm not clear on what the problem is with this issue.  That seems to be a "me" issue, as it was clear to you, but at the same time, I'm hesitant to merge something that you think is not quite complete because I have no idea :smile: .  If you could open the other PR and then I can merge them in at the same time, that'd be great.

**Comment by mattrose** [comment]
I think I'm starting to figure this one out after having looked at it and read your patch, and it looks good to me.  If you could either open a new bug or come up with a new PR for the other issue you mentioned, that would be great.  That way there's some evidence of it other than in a closed PR, in case you get busy with something else, or there's something else blocking your fix.

**Comment by Vulcalien** [comment]
Here is how to reproduce the issue.
1. Split the terminal
2. Zoom one of the terminal
3. Try to move to the other terminal (with keyboard shortcuts)

Current behavior:
nothing will happen, and the zoomed terminal will remain zoomed.

Desired behavior:
the terminal should unzoom and then move to the other terminal.

Other examples of "interactions" that should trigger an unzoom are a split, a rotation, a "new tab".
So with the changes in this PR, if you try to split, the zoomed terminal will first unzoom and then split as it should.

This is more or less how tmux handles the behavior as well.

***

I will make the new issue.

**Comment by mattrose** [comment]
Merging.  Sorry about the wait.

**Comment by Vulcalien** [comment]
Finally wrote the issue, I wanted to make sure to see the real problem. Apparently, it's focus lost.

**Pull request merged**
