### PR TITLE
custom_commands submenus via GUI

### PR DESCRIPTION
**Pull request by JordyProvost**
- Permit to create submenus in a more graphical way (instead of using '/' in command names)
- Fixes for indentation coherence (first level is 4 spaces, second is 8, third is 12, etc...)
- Clean some trailing spaces, and spaces only lines

Tested on Debian Strech and Buster without any problem.

### CODE REVIEW

**Comment by jordyprovost** [comment]
For information (may or may not be relevant).

I first suggest this change in 2017 (or even before), since i was needing the submenus feature for my work.
At this time, it was told me to repair indendations problems (which were previously existing in the plugin).
After that, the '/' workaround for creating submenus has been implemented.
Changes in terminator broke my forked plugin, so i have made my modifications again based on the launchpad version, and i have repaired indentation errors as asked.
I have made another pull_request https://code.launchpad.net/~jordy-provost/terminator/custom_commands_submenus/+merge/351362
As you see here "the whitespace changes make it hard to spot the actual code changes", yes i understand that, but i have done what i was asked previously.
I have see that this project has been migrated to GitHub, so i have taken my forked project, and backported last commits on it:
https://github.com/gnome-terminator/terminator/commit/23135f2ca5e2fbe87656797d9e1318862538fa4b#diff-04594ee4fb83ea8ec487e71ac13e1a99
https://github.com/gnome-terminator/terminator/commit/0f05cd8c8bc8077c4f5e425913f5dad6a4985eec#diff-04594ee4fb83ea8ec487e71ac13e1a99
https://github.com/gnome-terminator/terminator/commit/a3a67385fd1f0120fa4a5bb52ff47d04d19f8843#diff-04594ee4fb83ea8ec487e71ac13e1a99

**Comment by mattrose** [comment]
Thanks for this.  I'll pull this in and put it through its paces a little bit.  On the whitespace thing, that kinda sucks.  From an eyeball diff it looks OK. If I have any questions I'll ask

**Comment by mattrose** [comment]
Hmm, one nitpick.  If people have a custom command in a submenu using the current way ("foo/bar"), this patch will flatten all of their menus into one menu.  Is there a way for you to support both methods?

**Comment by jordyprovost** [comment]
Thanks for your answer.
That's sound relevant.

As i was looking into that, i have seen that my proposal is functionnaly less powerfull than the actual feature.

With the foo/bar thing, it is possible to imbricate several levels of submenus, for exemple foo/bar/foo2/bar2/my_command.
My proposal in the actual state only permit one level of submenus.

I think it's impossible to graphically show several levels of imbrication in the actual "preferences" GUI without reworking it entirely.

But maybe is it possible to mix the features like that:
- create submenus via gui (like my proposal)
- create sub-sub-sub... menus by using the foor/bar thing in the submenu column

I think this is a good trade-off as users can see the possibility of creating submenus directly in the GUI, and advanced users can also create imbrications like before.

So, here is what i want to do: rework my actual code to handle the foo/bar thing in the submenu column.

That my first point.

For the nitpick (maybe it is not one :smiley: ):
The downside of this: if a user define a command with the foo/bar thing in the command name *and* a submenu in the GUI, we have to choose how to handle the menu (old or new way).
In my point of view, the GUI must be privilegied (user expect the program to run following what is defined in GUI).

I propose the following approach: handle the foo/bar thing only if submenu is not defined or empty in config file.

Example:
- command name: "foo/bar/command_name"
- command submenu: undefined or ""
Code will change this for:
- command name: "command_name"
- command submenu: "foo/bar"
If the user open the "preferences" panel, he will see command_name in name column, and foo/bar in submenu column.

This way, config files will be updated to use the new feature in a transparent manner
If a submenu is already defined for a command, we dont handle the foo/bar thing, the command name will stay "foo/bar/command_name"

What do you think ?

**Comment by mattrose** [comment]
Sorry, I read this and didn't respond immediately, because I couldn't quite wrap my head around it on first read, then I forgot about it until now when I was reviewing PRs.  your suggested fix sounds perfect

**Comment by mattrose** [comment]
Any luck with this approach?

**Comment by jordyprovost** [comment]
My actual code is functionnaly at the level of the current plugin (to be simple, i can create sub-sub-sub menus via the "/" in menus name).
I have to implement the retrocompatibility part, not enought time ATM, but i'll work on this this ASAP.

Once done i think i have to make another pull request ?

**Comment by mattrose** [comment]
Nope, as long as you have the original branch around you can just push changes to it and they'll be automatically picked up

**Comment by mattrose** [comment]
Is this ready to go?

**Comment by jordyprovost** [comment]
It's just the complete feature (with multiple levels of submenus), but retrocompatibility is not here.

**Comment by mattrose** [comment]
Sorry, I thought that was what the last commit comment was indicating.  Glad to see you still working on this.

**Comment by mattrose** [comment]
Good to see you still working on this.  I'm pretty busy starting a new job for the next, but let me know if you need anything from me

**Comment by mattrose** [comment]
Are you still working on this?

**Comment by mattrose** [comment]
Sorry, this has been sitting too long.  Can you clean this up and resubmit?

**Pull request closed without merging**
