### PR TITLE
Add detachable tabs feature to preferences

### LINKED ISSUE #697: Disable detachable tabs flag
**Is your feature request related to a problem? Please describe.**
Hi, would it be possible to have a flag/config preference to disable detachable tabs introduced in #494? I often rearrange my tabs, and find myself accidentally detaching instead with the latest update.

**Describe the solution you'd like**
Option in preferences to disable detachable tab behaviour.

Strangely, I attempted to revert the commits locally and add a preference, but the tabs seemed to remain detachable.

### PR DESCRIPTION
**Pull request by zpalmtree**
Fixes #697.

Not sure why so much markup got changed, guess some new glade version thing.

### CODE REVIEW

**Comment by zpalmtree** [comment]
Merged your PR, thanks for the help!

**Comment by mattrose** [comment]
I'm probably blind, but I can't see the detachable tabs check box when I pull your code in?  Can you put up a screenshot or something to help me?

**Comment by zpalmtree** [comment]
> I'm probably blind, but I can't see the detachable tabs check box when I pull your code in? Can you put up a screenshot or something to help me?

It should appear here: 
image

Perhaps you have an existing terminator instance open? When I was testing out my changes if I had any other terminators open, it would reuse the old code and not reflect any new changes.

**Review by nautics889 — APPROVED** [review]
Everything works fine on for me. 

I see a toggle in preferences and it works correctly when i disable/enable one:
Screenshot 2023-04-17 234716

Thank you!

**Comment by mattrose** [comment]
all good now, sorry about the wait.

**Pull request merged**
