### PR TITLE
681 Plugin submission mouseless keyboard url open decoupled code

### PR DESCRIPTION
**Pull request by vssdeo**
Ref: https://github.com/gnome-terminator/terminator/issues/681

Resubmitting plugin for mousefree url handler on terminal with decoupled code and dependencies below that have to be fulfilled.

DEPENDENCIES:

https://github.com/gnome-terminator/terminator/pull/806
https://github.com/gnome-terminator/terminator/pull/809

### CODE REVIEW

**Comment by mattrose** [comment]
I think that this needs to pull the other PR in from the other branch.  I'll see if I can pull it in

**Comment by vssdeo** [comment]
You have already merged the dependency, not sure why the  ERROR terminatorlib/plugins/mousefree_url_handler.py - ImportError: cannot import name 'KeyBindUtil' from 'terminatorlib.plugin' (/home/runner/work/terminator/terminator/terminatorlib/plugin.py

Locally I updated my branch with master and copied the plugin it seems to work, let me check more on this

**Comment by mattrose** [comment]
This branch still doesn't have the merged code in it, so it will always fail the test.  You could merge the code from master and then push the merged branch back, that should fix it.

**Comment by vssdeo** [comment]
ok got it !

**Comment by mattrose** [comment]
Looks Good!  Thanks for this!

**Pull request merged**
