### PR TITLE
Add ability to configure cell width (font character spacing)

### PR DESCRIPTION
**Pull request by FernandoBasso**
Terminator already implements the VTE “cell height” feature. This PR implements “cell width”.

We also take the opportunity to refactor “line height“ to “cell height“ to match VTE terminology and to avoid having to related, similar features with two different naming style in the code base.

Thanks @mattrose for the help and encouragement <3.

terminator-cell-width

### CODE REVIEW

**Comment by mattrose** [comment]
See Gitter for feedback on this.  There's a few issues that need fixing before I can pull.

**Comment by FernandoBasso** [comment]
@mattrose Just pushed an amend to  the last commit based on your suggestions. Thanks once again for all the support.

**Comment by mattrose** [comment]
Looks good, thank you!  Sorry to be such a pain on this one, and sorry to be so long in looking this over, I've just been quite busy lately.

**Comment by FernandoBasso** [comment]
> Looks good, thank you! Sorry to be such a pain on this one, and sorry to be so long in looking this over, I've just been quite busy lately.

No problem at all. Thanks again for all the support @mattrose.

**Pull request merged**
