### PR TITLE
681 plugin submission plugin utility key binding mouseless keyboard url open

### PR DESCRIPTION
**Pull request by vssdeo**
Please Read: https://github.com/gnome-terminator/terminator/issues/681 for the changes.

### CODE REVIEW

**Comment by vssdeo** [comment]
Yes it’s already these for testing and comments / changes

**Comment by vssdeo** [comment]
While you are testing, do try, may be playing with two plugins in parallel may throw out more errors or conditions etc. I haven’t included this in PR and this sits in my branch.

https://github.com/vssdeo/terminator/tree/new-selecting-text-with-keyboard-shift-up-shift-down

**Comment by mattrose** [comment]
I had to throw the signal patch into the branch, and make a few more adjustments to terminatorlib/terminator.py to get it to work properly on any subsequent window but the 1st one. (I had to move the copy_other_signals method call from create_layout to new_window.)

I still would rather have the window get the signals from the plugin.  Getting it from the first window feels ... random somehow.  I tried messing with the plugin.py code to get it to load the signals from there, but have so far been unsuccessful.

**Comment by vssdeo** [comment]
I think I tried with re-loading plugins, can’t recall. Will try once back. 

There are use cases for both methods, like fork copying all structures for parent or the other where a new instance should be a new fresh start as per configs. Let me get back home in a day or two and try.

**Comment by vssdeo** [comment]
Hi @mattrose, I had done this to play around with reloading before, this was not final though, just to experiment. Calling the loaded module func was calling plugin ` __init__` again and worked on new window. I still need to check further with import mechanism and any side effects.

```
diff --git a/terminatorlib/plugin.py b/terminatorlib/plugin.py
index 8ab8ddf8..9b900e1e 100644
--- a/terminatorlib/plugin.py
+++ b/terminatorlib/plugin.py
@@ -73,7 +73,7 @@ class PluginRegistry(borg.Borg):
         """Load all plugins present in the plugins/ directory in our module"""
         if self.done:
             dbg('Already loaded')
-            return
+            #return
 
         config = Config()
 
@@ -93,9 +93,11 @@ class PluginRegistry(borg.Borg):
                     try:
                         module = __import__(plugin[:-3], None, None, [''])
                         for item in getattr(module, 'AVAILABLE'):
+                            func = getattr(module, item)
                             if item not in list(self.available_plugins.keys()):
-                                func = getattr(module, item)
                                 self.available_plugins[item] = func
+                            else:
+                                func()
 
                             if item not in config['enabled_plugins']:
                                 dbg('plugin %s not enabled, skipping' % item)

```

**Comment by vssdeo** [comment]
great ! so will you be making the change @mattrose along with your other changes ?

**Comment by mattrose** [comment]
Sure, I can pull this together.   I'll work something up as soon as I can.  Do you mind if I rebase the commit and split it up so that the plugin itself is separate from the supporting code for it?  I might even do the plugin as a separate PR.

Once that's done you should also be able to pull in the other plugin that you've been working on as a separate PR as well.

**Comment by vssdeo** [comment]
Sure @mattrose you are the boss, makes sense.

You mean the other mouse free selection :) yes hope other folks find it of any use. 

Anyways so let me know if anything from my side is needed !

**Comment by vssdeo** [comment]
closing this as this code is decoupled into diff components

**Pull request closed without merging**
