### PR TITLE
#513 Add auto-scroll down to the cursor position

### PR DESCRIPTION
**Pull request by marktimarev**
Resolving https://github.com/gnome-terminator/terminator/issues/513

### CODE REVIEW

**Comment by marktimarev** [comment]
I propose to watch for the event of cursor movement (it moves when you type or just manually move it with arrow keys). And it it moves to scroll at its position.
Works well for me.

**Comment by mattrose** [comment]
Looks good, I'm just gonna check this out and run a sanity test before merging.

**Comment by marktimarev** [comment]
Oh, I just understood that it will not work properly if there's some task running and its output, printing into the terminal, moves the cursor. I mean, if I run something in the background and want to scroll up to check something, the scroll will jump down to the cursor as the task output something.

At least, the original GNOME Terminal behaves well with such a case.

We need to somehow check that cursor movement is caused by pressing a key. We could of course just catch key down event, save the cursor position, and on key up event check if the position is changed. But I think it's a too dirty solution :(

**Comment by marktimarev** [comment]
Finally, this is what we need. The event _commit_ is "Emitted whenever the terminal receives input from the user and prepares to send it to the child process."

Now auto-scroll works exactly like in Terminal.
Please check

**Comment by mattrose** [comment]
Thanks for updating, I was just about to start doing some research.  I'll pull it down and check rt now

**Pull request closed without merging**
