### PR TITLE
Fix fallback for getting the current working directory

### PR DESCRIPTION
**Pull request by terceiro**
This fixes a regression introduced in 40ba659f6d19001b964f72390153b81e33e1908a

### CODE REVIEW

**Comment by mattrose** [comment]
Thanks for this.

**Comment by mattrose** [comment]
How did you come across this?

**Comment by terceiro** [comment]
> How did you come across this?

just running terminator from the git repository, master branch

**Comment by terceiro** [comment]
thanks for the quick merge BTW

**Pull request merged**
