### PR TITLE
Add Gentoo, sort the order of distributions

### PR DESCRIPTION
**Pull request by DarthGandalf**

### CODE REVIEW

**Comment by mckellyln** [comment]
Just a suggestion, maybe also add some text about shebang and python version ?
python3 setup.py install ...
etc.

**Comment by DarthGandalf** [comment]
@mckellyln sorry, how is it related to linux distros? Users are supposed to run `apt`, `emerge` or similar to install terminator there, not `setup.py`.

**Comment by mckellyln** [comment]
Its not, sorry.  This rewally should be a separate suggestion and PR.  I was just suggesting it because its a very small change for the same INSTALL file.  Sorry.

**Comment by lazyfrosch** [comment]
@DarthGandalf thank you, can you give me a few links for Gentoos source and bugs for Terminator? I'm maintaining the list here: https://github.com/gnome-terminator/terminator/wiki/Distributions

**Comment by DarthGandalf** [comment]
https://packages.gentoo.org/packages/x11-terms/terminator
Source: https://github.com/gentoo/gentoo/tree/master/x11-terms/terminator
Bugs: https://bugs.gentoo.org/

**Comment by lazyfrosch** [comment]
Thanks, added that

**Pull request merged**
