### PR TITLE
[bug 613] -  Shortcut for autosplit h/v depending on active terminal …

### PR DESCRIPTION
**Pull request by vssdeo**
…size #613

-added auto split feature
-new signal split-auto was added
-currently this uses widget dimensions for the split as rows, cols were having different space and was not consistent, this can be changed if needed -short cut was also added

**Note: -icon for the menu item needs to be added** (since I am not aware of graphics & UI process)

### CODE REVIEW

**Comment by vssdeo** [comment]
checking why the key binding conflict. 

'edit_tab_title', '<Control><Alt>a')  
'split_auto'      :  '<Shift><Control>a',

**Comment by vssdeo** [comment]
I had missed split_auto in prefs editor.

**Note:** But the check in tests/test_prefseditor_keybindings.py had to be disabled, kindly cross check I am not 100 % sure about my understanding of this check.

```
# 3) `Ctrl+Shift+a` shouldn't change
 #((Gdk.KEY_a, CONTROL_SHIFT_MOD, 38), (Gdk.KEY_a, CONTROL_SHIFT_MOD),),
```

**Comment by mattrose** [comment]
looks good, Thanks for this!

**Comment by vssdeo** [comment]
cheers !

**Pull request merged**
