### PR TITLE
Remove Encoding settings (deprecated)

### PR DESCRIPTION
**Pull request by Vulcalien**
Issue #534

All I did was remove code. I don't expect anything breaking, since it doesn't seem to be connected to other code.

## List of changes
- The file `encoding.py` was entirely deleted.
- The GUI widget in `preferences.glade` used to select encoding was removed, along with the signal handlers in `prefseditor.py`
- The code that generated the context menu entry (file `terminal_popup_menu.py`) was removed, along with the signal handler in `terminal.py`
- The settings `encoding` and `active_encodings` were removed

I don't know if there is a way to test this, since it's a feature removal. I just opened the menus and no error messages were being printed.

### CODE REVIEW

**Comment by mattrose** [comment]
:heavy_check_mark: Less Code
:heavy_check_mark: Smaller  context menu

I like it!

**Comment by jhalx** [comment]
How should I go about changing the terminal encoding after the option has been removed?

**Comment by jhalx** [comment]
> How should I go about changing the terminal encoding after the option has been removed?

One of the biggest influencing factors of my use of the terminal is that it is very convenient to modify the terminal encoding

**Comment by jhalx** [comment]
I hope to add this feature back to the built-in plugin and set it to be turned off by default. Although most people don't need this feature, it is indispensable.

> How should I go about changing the terminal encoding after the option has been removed?

I hope to add this feature back to the built-in plugin and set it to be turned off by default. Although most people don't need this feature, it is indispensable.

**Comment by jhalx** [comment]
> How should I go about changing the terminal encoding after the option has been removed?

I hope to add this feature back to the built-in plugin and set it to be turned off by default. Although most people don't need this feature, it is indispensable.

**Comment by Vulcalien** [comment]
The reason we removed it was that vte, the terminal GTK component, deprecated it. It would be up to them to add it back, and then we could revert this change as well.

It is very unfortunate, but maybe a command like `luit` could help.

**Pull request merged**
